@startuml uploadFile
autonumber 1.1.1
User -> perliteSyncClient: click upload file
perliteSyncClient -> perliteContract: get metadata
perliteContract --> perliteSyncClient: metadata
perliteSyncClient -> perliteSyncClient: parse metadata
perliteSyncClient -> perliteSyncClient: 是否有data.json文件

group 有data.json文件
    perliteSyncClient -> perliteSyncClient: 有，判断更新
end

group 没有data.json文件
    perliteSyncClient -> perliteSyncClient: 没有，生成data.json文件
    perliteSyncClient -> perliteSyncClient: 下载文件
end

@enduml
